
# This file is useful to developers of the package, not so much for users of the package.
# Users should see "installPackage.R" to install the package.


library(Rcpp)
library(devtools)
library(roxygen2)

CatContPackageVersion = "0.7.2"
addingDataSets = FALSE

baseDir = "~/../Programming/R/CatContModel/"

packagePath = baseDir
packageName = "CatContModel"
fullPackagePath = paste( packagePath, packageName, "/", sep="")
packageLocation = paste( packagePath, packageName, sep="")




modelFilesDir = paste(baseDir, "source/cpp/", sep="")
modelFiles = c("Compilation.h", "CCM_BayesianModel.h", "CCM_BayesianModel.cpp", "CCM_BayesianModel_Misc.cpp","RInterface.cpp", "CCM_Util.h", "CCM_Util.cpp", "CCM_Linear.h", "CCM_Linear.cpp", "CCM_Circular.h", "CCM_Circular.cpp", "VonMisesLut/VonMisesLut.h", "VonMisesLut/VonMisesLut.cpp")
modelFiles = paste(modelFilesDir, modelFiles, sep="")

gsBase = paste(modelFilesDir, "GibbsSampler/", sep="")
gsFiles = c("GibbsSampler.h", "GibbsSampler.cpp", "UtilityFunctions.h", "UtilityFunctions.cpp")
gsFiles = paste( gsBase, gsFiles, sep="" )

cpp_files = c(modelFiles, gsFiles)

rFilesDir = paste(baseDir, "/source/R/", sep="")
rFiles = dir( rFilesDir )
rFiles = paste( rFilesDir, rFiles, sep="" )




#include the package documentation
rFiles = c(rFiles, paste(packagePath, "docs/toCopy/CatContModel-package.R", sep="") )
#And the data set documentation
if (addingDataSets) {
	rFiles = c(rFiles, paste(packagePath, "examples/betweenItem/betweenDataDoc.R", sep="") )
}


#delete the old files
packageFiles = dir( packageLocation, recursive = TRUE)
file.remove( paste(fullPackagePath, packageFiles, sep="") )

#move new files
Rcpp.package.skeleton(packageName, path=packagePath, cpp_files=cpp_files, code_files=rFiles, 
												force=TRUE, example_code=FALSE, attributes = TRUE,
											author="Kyle O Hardman", license="MIT + file LICENSE", email="kylehardman@gmail.com")


#Data sets
if (addingDataSets) {
	betweenItemData = read.delim( paste(packagePath, "examples/betweenItem/betweenItemData.txt", sep="") )
	devtools::use_data(betweenItemData, pkg = packageLocation)
	betweenItemParameters = read.delim( paste(packagePath, "examples/betweenItem/betweenItemParameters.txt", sep="") )
	devtools::use_data(betweenItemParameters, pkg = packageLocation)
}


roxygen2::roxygenise( packageLocation )


#get rid of the autogenerated package documentation
file.remove( paste( fullPackagePath, "man/CatContModel-package.Rd", sep="") )
file.remove( paste( fullPackagePath, "Read-and-delete-me", sep="") )

#Append Imports and Suggests to DESCRIPTION
devtools::use_package("CircStats", pkg=packageLocation)
devtools::use_package("polspline", pkg=packageLocation)
devtools::use_package("msm", pkg=packageLocation)
devtools::use_package("R.rsp", type = "Suggests", pkg=packageLocation)
devtools::use_package("LineChart", type = "Suggests", pkg=packageLocation)


#Modify the DESCRIPTION
dcf = read.dcf( paste(fullPackagePath, "DESCRIPTION", sep="") )
dcf[,"Title"] = "Categorical and Continuous Working Memory Models for Delayed-Estimation Tasks"
dcf[,"Description"] = "Perform parameter estimation, posterior distribution analysis, and model comparison with the models used by Hardman, Vergauwe, & Ricker (2017). The models in this package are for delayed-estimation tasks that are commonly used in the working memory literature. The models a difficult to implement and work with for a variety of reasons, hence the value of this package. Hierarchical Bayesian implementations of between-item and within-item model variants used by Hardman, Vergauwe, and Ricker are included, as is the Zhang & Luck (2008) model. For any of these models, functions in this package allow you to relatively easily estimate the model parameters, plot parameter values, calculate posterior means and credible intervals, perform tests of the effect of task conditions on parameters, and calculate model fit statistics, among other things."
dcf[,"Author"] = "Kyle O Hardman"
dcf[,"Maintainer"] = "Kyle O Hardman <kylehardman@gmail.com>"
dcf[,"Version"] = CatContPackageVersion

dependsCol = matrix("R (>= 3.3)", nrow=1, ncol=1, dimnames = list(c(), "Depends"))

vignBuilder = matrix("R.rsp", nrow=1, ncol=1, dimnames = list(c(), "VignetteBuilder"))

dcf = cbind(dcf, dependsCol, vignBuilder)

write.dcf(dcf, file = paste(fullPackagePath, "DESCRIPTION", sep="") )


#Copy over CITATION and LICENSE
dir.create(paste(fullPackagePath, "inst/", sep=""))
#file.copy(from = paste(baseDir, "docs/toCopy/CITATION", sep=""), to = paste(fullPackagePath, "inst/CITATION", sep=""))
file.copy(from = paste(baseDir, "LICENSE.md", sep=""), to = paste(fullPackagePath, "LICENSE", sep=""))

#Copy over manual and supporting asis file
file.copy(from = paste0(baseDir, "docs/introduction/Introduction.pdf"), 
					to = paste0(fullPackagePath, "inst/doc/Introduction.pdf"))

file.copy(from = paste0(baseDir, "docs/toCopy/Introduction.pdf.asis"), 
					to = c(paste0(fullPackagePath, "inst/doc/Introduction.pdf.asis"),
								 paste0(fullPackagePath, "vignettes/Introduction.pdf.asis")
								 )
					)



#At this point, there is a proper R package structure in packageLocation
#You may not be able to do the four steps below in the same R session:
#I have had issues with building the binary package after installing from source. YMMV.


#Install the package from source.
install.packages(pkgs=paste(packagePath, packageName, sep=""), repos=NULL, type="source")


#Check the package (as for submission to CRAN).
devtools::check(packageLocation)


#Note to self: Make sure that you remember to increment the version number before you
#run either of the following commands!!!

#Build source archive of package
devtools::build(packageLocation, path=paste(baseDir, "packaged/", sep="") )

#Build binary archive of package
devtools::build(packageLocation, path=paste(baseDir, "packaged/", sep=""), binary = TRUE)




